--- 
- 
  become: true
  connection: local
  gather_facts: false
  hosts: localhost
  vars:
    ansible_become_pass: '{{password}}'
    
  tasks: 
    - 
      command: "docker run --privileged -itd --name='{{container}}' doc1:1.0"
      name: "Create container '{{container}}'"
