--- 
- 
  become: true
  connection: local
  gather_facts: false
  hosts: localhost
  vars:
    ansible_become_pass: '{{password}}'
    
  tasks: 
    - 
      command: "docker run --privileged -itd --name='{{container}}' doc1:1.0"
      name: "Create container '{{container}}'"
      
    -
      name: install ssh service
      shell: 'docker exec --privileged {{ container }} apt install -y ssh'
      become: yes
      ignore_errors: yes
      
    -
      name: starting ssh service
      shell: 'docker exec --privileged {{ container }} service ssh start'
      become: yes
      ignore_errors: yes
