--- 
- 
  become: true
  connection: local
  gather_facts: false
  hosts: localhost
  vars:
    ansible_become_pass: '{{password}}'

  tasks: 
  - name: "Stop Container '{{container}}'"
    command: "docker stop {{container}}"
    become: yes
    ignore_errors: yes

  - name: "Remove Container '{{container}}'"
    command: "docker rm {{container}}"
    become: yes
    ignore_errors: yes
